[
  {
    "number": 148,
    "title": "Potential BUG in pack.py?",
    "created_at": "2024-12-27T03:12:46Z",
    "closed_at": "2024-12-29T04:35:36Z",
    "labels": [],
    "url": "https://github.com/microsoft/VPTQ/issues/148",
    "body": "I encountered an `AssertionError` while using the code in the algorithm branch to quantize the LLaMA3.1-8B model with the setting `num_res_centroids > num_centroids`. I believe that setting `num_res_centroids > num_centroids` is a valid configuration. It seems that this issue might be related to **line 128 in `pack.py`**. Specifically, I propose the following change:\n```python\n#res_indices = ((unpack_indice >> index_bits) & ((1 << index_bits) - 1)).view(torch.uint64).to(torch.int64)\nres_indices = ((unpack_indice >> index_bits) & ((1 << res_bits) - 1)).view(torch.uint64).to(torch.int64)\n```\nCould you please review this part of the code and confirm if this modification is appropriate? ",
    "comments_url": "https://api.github.com/repos/microsoft/VPTQ/issues/148/comments",
    "author": "ForAxel",
    "comments": [
      {
        "user": "YangWang92",
        "created_at": "2024-12-27T03:23:26Z",
        "body": "Let me check, thanks for your feedback!"
      },
      {
        "user": "YangWang92",
        "created_at": "2024-12-27T08:03:25Z",
        "body": "Hi @ForAxel,\nI think it is a bug, and can you help me to pull a request to fix it. You can be a contributor of the project. \n\nThanks!\nYang"
      },
      {
        "user": "YangWang92",
        "created_at": "2024-12-29T04:35:35Z",
        "body": "merged! Thanks for your contribution!"
      }
    ]
  },
  {
    "number": 119,
    "title": "When I use the parameter npercent=1 to quantize the model, I have the following problem\uff1a",
    "created_at": "2024-11-15T14:35:02Z",
    "closed_at": "2024-11-16T05:08:32Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/microsoft/VPTQ/issues/119",
    "body": "/VPTQ/vptq/vptq.py\", line 443, in get_error\n    weight = weight.reshape(qweight.shape)\nRuntimeError: shape '[3584, 3548]' is invalid for input of size 12845056\n\n",
    "comments_url": "https://api.github.com/repos/microsoft/VPTQ/issues/119/comments",
    "author": "half-lang",
    "comments": [
      {
        "user": "YangWang92",
        "created_at": "2024-11-16T03:51:21Z",
        "body": "Could you please list all the parameters? I suspect you might not have set vec_len for outlier. \nHere is an example, which allocates an outlier codebook (vector length = 4, size = 256) for **1%** outlier:\n```bash\nCUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python run_vptq.py \\\n        --model_name Qwen/Qwen2.5-7B-Instruct \\\n        --output_dir outputs/Qwen2.5-7B-Instruct/ \\\n        --vector_lens **4** 8 \\\n        --group_num 1 \\\n        --num_centroids **256** 65536 \\\n        --num_res_centroids -1 256 \\\n        --npercent **1** \\\n        --blocksize 128 \\\n        --new_eval \\\n        --seq_len 8192 \\\n        --kmeans_mode hessian \\\n        --num_gpus 8 \\\n        --enable_perm \\\n        --enable_norm \\\n        --save_model \\\n        --save_packed_model \\\n        --hessian_path Hessians-Qwen2.5-7B-Instruct-6144-8k \\\n        --inv_hessian_path InvHessians-Qwen2.5-7B-Instruct-6144-8k \\\n        --ktol 1e-5 --kiter 100\n```"
      },
      {
        "user": "half-lang",
        "created_at": "2024-11-16T04:53:07Z",
        "body": "thanks so much for your reply\uff1bI can quantize the model now\uff01"
      }
    ]
  }
]