[
  {
    "number": 130,
    "title": "RayTaskError with hf_transfer or ray.init()",
    "created_at": "2025-01-30T17:28:28Z",
    "closed_at": "2025-02-03T09:07:40Z",
    "labels": [],
    "url": "https://github.com/huggingface/open-r1/issues/130",
    "body": "I have met the error as follows, the error output is so long that I have to copy the last lines:\nRayTaskError(RuntimeError): [36mray::run_inference_one_model()[39m (pid=602229, ip=115.154.137.9)\nException: Failed too many failures in parallel (3): Request: error decoding response body (no permits available)\n\nThe above exception was the direct cause of the following exception:\n\n[36mray::run_inference_one_model()[39m (pid=602229, ip=115.154.137.9)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/lighteval/models/vllm/vllm_model.py\", line 336, in \nrun_inference_one_model\n    llm = LLM(**model_args)\n          ^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/utils.py\", line 986, in inner\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/entrypoints/llm.py\", line 230, in __init__\n    self.llm_engine = self.engine_class.from_engine_args(\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/engine/llm_engine.py\", line 517, in \nfrom_engine_args\n    engine = cls(\n             ^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/engine/llm_engine.py\", line 273, in __init__\n    self.model_executor = executor_class(vllm_config=vllm_config, )\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py\", line 26, in\n__init__\n    super().__init__(*args, **kwargs)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/executor_base.py\", line 36, in __init__\n    self._init_executor()\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py\", line 64, in \n_init_executor\n    self._init_workers_ray(placement_group)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py\", line 278, in \n_init_workers_ray\n    self._run_workers(\"load_model\",\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py\", line 407, in \n_run_workers\n    self.driver_worker.execute_method(method, *driver_args,\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/worker_base.py\", line 468, in \nexecute_method\n    raise e\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/worker_base.py\", line 459, in \nexecute_method\n    return executor(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/worker.py\", line 155, in load_model\n    self.model_runner.load_model()\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/model_runner.py\", line 1096, in load_model\n    self.model = get_model(vllm_config=self.vllm_config)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py\", line 12,\nin get_model\n    return loader.load_model(vllm_config=vllm_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 366, \nin load_model\n    loaded_weights = model.load_weights(\n                     ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py\", line 506, in \nload_weights\n    return loader.load_weights(weights)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 237, in \nload_weights\n    autoloaded_weights = set(self._load_module(\"\", self.module, weights))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 189, in \n_load_module\n    for child_prefix, child_weights in self._groupby_prefix(weights):\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 103, in \n_groupby_prefix\n    for prefix, group in itertools.groupby(weights_by_parts,\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 100, in \n<genexpr>\n    weights_by_parts = ((weight_name.split(\".\", 1), weight_data)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 342, \nin _get_all_weights\n    yield from self._get_weights_iterator(primary_weights)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 298, \nin _get_weights_iterator\n    hf_folder, hf_weights_files, use_safetensors = self._prepare_weights(\n                                                   ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 251, \nin _prepare_weights\n    hf_folder = download_weights_from_hf(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/weight_utils.py\", line\n255, in download_weights_from_hf\n    hf_folder = snapshot_download(\n                ^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py\", line 114, in \n_inner_fn\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py\", line 294, in \nsnapshot_download\n    _inner_hf_hub_download(file)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py\", line 270, in \n_inner_hf_hub_download\n    return hf_hub_download(\n           ^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py\", line 114, in \n_inner_fn\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 860, in \nhf_hub_download\n    return _hf_hub_download_to_cache_dir(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 1009, in \n_hf_hub_download_to_cache_dir\n    _download_to_tmp_and_move(\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 1543, in \n_download_to_tmp_and_move\n    http_get(\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 437, in \nhttp_get\n    raise RuntimeError(\nRuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better \nerror handling.\n(run_inference_one_model pid=602235) Calling ray.init() again after it has already been called. [repeated 7x across cluster]RayTaskError(RuntimeError): [36mray::run_inference_one_model()[39m (pid=602229, ip=115.154.137.9)\nException: Failed too many failures in parallel (3): Request: error decoding response body (no permits available)\n\nThe above exception was the direct cause of the following exception:\n\n[36mray::run_inference_one_model()[39m (pid=602229, ip=115.154.137.9)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/lighteval/models/vllm/vllm_model.py\", line 336, in \nrun_inference_one_model\n    llm = LLM(**model_args)\n          ^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/utils.py\", line 986, in inner\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/entrypoints/llm.py\", line 230, in __init__\n    self.llm_engine = self.engine_class.from_engine_args(\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/engine/llm_engine.py\", line 517, in \nfrom_engine_args\n    engine = cls(\n             ^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/engine/llm_engine.py\", line 273, in __init__\n    self.model_executor = executor_class(vllm_config=vllm_config, )\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py\", line 26, in\n__init__\n    super().__init__(*args, **kwargs)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/executor_base.py\", line 36, in __init__\n    self._init_executor()\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py\", line 64, in \n_init_executor\n    self._init_workers_ray(placement_group)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py\", line 278, in \n_init_workers_ray\n    self._run_workers(\"load_model\",\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py\", line 407, in \n_run_workers\n    self.driver_worker.execute_method(method, *driver_args,\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/worker_base.py\", line 468, in \nexecute_method\n    raise e\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/worker_base.py\", line 459, in \nexecute_method\n    return executor(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/worker.py\", line 155, in load_model\n    self.model_runner.load_model()\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/worker/model_runner.py\", line 1096, in load_model\n    self.model = get_model(vllm_config=self.vllm_config)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py\", line 12,\nin get_model\n    return loader.load_model(vllm_config=vllm_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 366, \nin load_model\n    loaded_weights = model.load_weights(\n                     ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py\", line 506, in \nload_weights\n    return loader.load_weights(weights)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 237, in \nload_weights\n    autoloaded_weights = set(self._load_module(\"\", self.module, weights))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 189, in \n_load_module\n    for child_prefix, child_weights in self._groupby_prefix(weights):\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 103, in \n_groupby_prefix\n    for prefix, group in itertools.groupby(weights_by_parts,\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/models/utils.py\", line 100, in \n<genexpr>\n    weights_by_parts = ((weight_name.split(\".\", 1), weight_data)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 342, \nin _get_all_weights\n    yield from self._get_weights_iterator(primary_weights)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 298, \nin _get_weights_iterator\n    hf_folder, hf_weights_files, use_safetensors = self._prepare_weights(\n                                                   ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py\", line 251, \nin _prepare_weights\n    hf_folder = download_weights_from_hf(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/vllm/model_executor/model_loader/weight_utils.py\", line\n255, in download_weights_from_hf\n    hf_folder = snapshot_download(\n                ^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py\", line 114, in \n_inner_fn\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py\", line 294, in \nsnapshot_download\n    _inner_hf_hub_download(file)\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py\", line 270, in \n_inner_hf_hub_download\n    return hf_hub_download(\n           ^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py\", line 114, in \n_inner_fn\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 860, in \nhf_hub_download\n    return _hf_hub_download_to_cache_dir(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 1009, in \n_hf_hub_download_to_cache_dir\n    _download_to_tmp_and_move(\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 1543, in \n_download_to_tmp_and_move\n    http_get(\n  File \"/home/yhpeng/anaconda3/envs/openr1/lib/python3.11/site-packages/huggingface_hub/file_download.py\", line 437, in \nhttp_get\n    raise RuntimeError(\nRuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better \nerror handling.\n(run_inference_one_model pid=602235) Calling ray.init() again after it has already been called. [repeated 7x across cluster]\nI use 4 cards Geforce RTX 4090, could anyone help me? Thanks\uff01",
    "comments_url": "https://api.github.com/repos/huggingface/open-r1/issues/130/comments",
    "author": "pyh314",
    "comments": [
      {
        "user": "sam-schorb",
        "created_at": "2025-01-30T22:06:06Z",
        "body": "The error comes from Hugging Face's experimental \"hf_transfer\" downloader. Try this:\n1. **Quickest fix**: Disable hf_transfer by running:\n```bash\nexport HF_HUB_ENABLE_HF_TRANSFER=\"false\"\npython your_script.py\n```\n\n2. **Offline approach**: Download model weights locally and point VLLM to the local path:\n```python\nmodel = LLM(model=\"<local folder path>\", ...)\n```\n\n3. **Update dependencies**: Ensure you have recent versions:\n```bash\npip install --upgrade huggingface_hub transformers vllm\n```\n"
      }
    ]
  }
]