[
  {
    "number": 1971,
    "title": "Hello,",
    "created_at": "2024-01-16T15:45:29Z",
    "closed_at": "2024-05-15T19:51:01Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1971",
    "body": "Hello, there has been problem on your osint tool or mine i dont really know, may you please help me.?\r\n\r\nTraceback (most recent call last):\r\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"C:\\Users\\^^^^^^\\sherlock\\sherlock\\__main__.py\", line 21, in <module>\r\n    import sherlock\r\n  File \"C:\\Users\\^^^^^^\\sherlock\\sherlock\\sherlock.py\", line 20, in <module>\r\n    import requests\r\n  File \"C:\\Users\\^^^^^^\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\__init__.py\", line 43, in <module>\r\n    import urllib3\r\n  File \"C:\\Users\\^^^^^^\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\__init__.py\", line 7, in <module>\r\n    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url\r\n  File \"C:\\Users\\^^^^^^\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 11, in <module>\r\n    from .exceptions import (\r\n  File \"C:\\Users\\^^^^^^\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\exceptions.py\", line 2, in <module>\r\n    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead\r\nModuleNotFoundError: No module named 'urllib3.packages.six.moves'\r\n\r\n\r\nThank you.,",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1971/comments",
    "author": "rapable",
    "comments": [
      {
        "user": "matheusfelipeog",
        "created_at": "2024-01-19T19:17:16Z",
        "body": "Hi @rapable, thanks for opening this issue.\r\n\r\nI can't help you with just this information. What exactly did you execute to get to this message in the traceback?"
      },
      {
        "user": "sdushantha",
        "created_at": "2024-05-15T19:51:01Z",
        "body": "Closing this issue as it is an issue with user's environment and not Sherlock"
      }
    ]
  },
  {
    "number": 1960,
    "title": "--timeout error",
    "created_at": "2023-12-23T11:16:25Z",
    "closed_at": "2023-12-25T02:02:29Z",
    "labels": [
      "bug",
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1960",
    "body": "<!--\r\n\r\n######################################################################\r\n  WARNING!\r\n  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE.\r\n######################################################################\r\n\r\n-->\r\n\r\n## Checklist\r\n<!--\r\nPut x into all boxes (like this [x]) once you have completed what they say.\r\nMake sure complete everything in the checklist.\r\n-->\r\n- [X] I'm asking a question regarding Sherlock\r\n- [ ] My question is not a tech support question.\r\n\r\n\r\n## Question\r\n\r\nim having the following error: sherlock: error: argument --timeout: invalid timeout_check value: '1'\r\nWhat should I write as argument of --timeout?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1960/comments",
    "author": "alvaro2203",
    "comments": [
      {
        "user": "Lukkeboi09",
        "created_at": "2023-12-24T20:20:08Z",
        "body": "I am having the exact same problem, so if someone gets the answer tell us!"
      },
      {
        "user": "matheusfelipeog",
        "created_at": "2023-12-25T01:57:57Z",
        "body": "Thank you for opening this issue, @alvaro2203 ðŸ˜„ \r\n\r\nI checked and found that the function responsible for validating and converting the value provided for the `--timeout` flag has an incorrect implementation.\r\n\r\nI will fix this. Once fixed, you should update your local clone with:\r\n\r\n```bash\r\ngit pull origin master\r\n```"
      },
      {
        "user": "matheusfelipeog",
        "created_at": "2023-12-25T02:03:42Z",
        "body": "Done âœ…"
      }
    ]
  },
  {
    "number": 1883,
    "title": " stop searching",
    "created_at": "2023-09-15T13:48:53Z",
    "closed_at": "2024-11-04T23:37:57Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1883",
    "body": "How to stop searching,\r\n when running \"python3 sherlock user123\" ???\r\n",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1883/comments",
    "author": "fl1pe",
    "comments": [
      {
        "user": "AgentXMan",
        "created_at": "2023-09-21T05:52:47Z",
        "body": "hello! i am not sure if there is a feature like that yet, if there isnt then i would like to contribute in adding that feature."
      },
      {
        "user": "2br-2b",
        "created_at": "2023-09-22T16:55:20Z",
        "body": "If you're in the middle of searching and you want to stop, press ctrl + c"
      }
    ]
  },
  {
    "number": 1794,
    "title": "Where is repl.it and google cloud shell link?",
    "created_at": "2023-05-16T09:57:51Z",
    "closed_at": "2023-05-16T10:04:08Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1794",
    "body": "Was watching a video made by NetworkChuck and under installation he has a repl.it and google cloud link. Where the hell did they go?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1794/comments",
    "author": "OMT2011",
    "comments": [
      {
        "user": "reemandstuff",
        "created_at": "2023-06-15T14:04:43Z",
        "body": "please update me if u knew \r\n"
      }
    ]
  },
  {
    "number": 1667,
    "title": "I don't have the option to run it in google cloud shell",
    "created_at": "2023-01-20T11:14:58Z",
    "closed_at": "2023-01-25T12:01:18Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1667",
    "body": "Why do I not have the option to run it in google cloud shell?\r\n",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1667/comments",
    "author": "jj09n",
    "comments": [
      {
        "user": "Phantomclan",
        "created_at": "2023-01-21T03:29:18Z",
        "body": "I don't have that option either"
      },
      {
        "user": "sdushantha",
        "created_at": "2023-01-25T12:01:17Z",
        "body": "This option has been removed. There are many tutorials out that show the Google Cloud shell option that is now outdated"
      }
    ]
  },
  {
    "number": 1593,
    "title": "How to fix this error",
    "created_at": "2022-10-27T15:28:17Z",
    "closed_at": "2023-02-04T17:17:07Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1593",
    "body": "[end of output]\r\n\r\nnote: This error originates from a subprocess, and is likely not a problem with pip.\r\nERROR: Failed building wheel for numpy\r\nFailed to build numpy\r\nERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects\r\n~/sherlock $",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1593/comments",
    "author": "Dstar001",
    "comments": [
      {
        "user": "rskbansal",
        "created_at": "2022-10-31T13:50:32Z",
        "body": "Try installing `numpy` manually using\r\n```\r\npip install numpy\r\n```"
      }
    ]
  },
  {
    "number": 1464,
    "title": "How to use full name instead of just single word? for example python3 sherlock first last",
    "created_at": "2022-09-16T03:22:24Z",
    "closed_at": "2022-09-24T12:29:20Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1464",
    "body": "I am not sure the full name search function is added to the program or not. I was trying to hunt down my own social media but I couldn't find because I have space separate user name like first last-name",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1464/comments",
    "author": "Tula-Magar",
    "comments": [
      {
        "user": "tory1103",
        "created_at": "2022-09-20T00:25:32Z",
        "body": "You could try adding quotation marks like in the example below:\r\npython3 sherlock \"first last-name\""
      }
    ]
  },
  {
    "number": 1426,
    "title": "Python 3.10.4",
    "created_at": "2022-08-04T10:19:53Z",
    "closed_at": "2022-08-05T06:04:33Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1426",
    "body": "Will Sherlock work with python3.10.4",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1426/comments",
    "author": "Nullpython3950",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2022-08-05T06:04:33Z",
        "body": "Yes"
      }
    ]
  },
  {
    "number": 1216,
    "title": "Help",
    "created_at": "2021-12-24T04:27:58Z",
    "closed_at": "2021-12-24T09:57:53Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1216",
    "body": "Traceback (most recent call last):\r\n  File \"C:\\Users\\user\\Downloads\\sherlock-master\\sherlock-master\\sherlock\\sherlock.py\", line 18, in <module>\r\n    import requests\r\nModuleNotFoundError: No module named 'requests'\r\n",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1216/comments",
    "author": "pvaranawat",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2021-12-24T09:57:53Z",
        "body": "Please read the README.md file. You need to install the required modules."
      }
    ]
  },
  {
    "number": 1029,
    "title": "Compatibility ",
    "created_at": "2021-03-29T13:48:40Z",
    "closed_at": "2021-06-27T09:59:11Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1029",
    "body": "## Can I run this on QPython 3L (Mobile Python)?\n",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1029/comments",
    "author": "m0ulee",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2021-06-27T09:59:11Z",
        "body": "This question is regarding your environment and not Sherlock it self. \r\n\r\nI have never heard of QPython 3L so that is something I unfortunately cannot answer. Try running it yourself and see what happens."
      }
    ]
  },
  {
    "number": 1007,
    "title": "Package and publish to pypi",
    "created_at": "2021-03-13T14:01:11Z",
    "closed_at": "2021-03-13T14:47:06Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/1007",
    "body": "## Checklist\r\n\r\n- [x] I'm asking a question regarding Sherlock\r\n- [x] My question is not a tech support question.\r\n\r\n## Could you publish sherlock on pypi ?\r\n\r\nIt would be helpful if users can just do `pip install sherlock` to install sherlock  \r\nIf the current developers are busy i could volunteer to be the pypi maintainer of this project",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/1007/comments",
    "author": "atharvakadlag",
    "comments": [
      {
        "user": "davins90",
        "created_at": "2023-01-27T10:57:49Z",
        "body": "Hi, are there some news about this possible implementation? Thanks"
      }
    ]
  },
  {
    "number": 898,
    "title": "Unable to update to latest site list",
    "created_at": "2020-12-14T18:36:52Z",
    "closed_at": "2020-12-18T05:41:03Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/898",
    "body": "I ran the update and the list of sites wasn't updates. I pulled the list from github and entered it into a new sites.md list, but i'm still getting results from the _old_ list that hangs after Zhihu\r\n\r\nThis is the command I ran to update: **python3.8 -m pip install -U -r /home/tony/Downloads/sherlock/requirements.txt**",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/898/comments",
    "author": "tonyscardina",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-12-18T05:41:03Z",
        "body": "Running the command above only updates the modules that are needed for Sherlock to run. If you want the latest version of Sherlock, you have to reclone or download it from this repo. We currently do not have an option to forcefully update Sherlock from the command line."
      }
    ]
  },
  {
    "number": 873,
    "title": "ModuleNotFoundError: No module named 'requests'",
    "created_at": "2020-11-23T05:05:16Z",
    "closed_at": "2020-11-23T08:44:24Z",
    "labels": [
      "invalid",
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/873",
    "body": "I am using kali linux\r\n```\r\nkali@kali:~/Downloads/sherlock$ uname -a\r\nLinux kali 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux\r\n```\r\nAfter install all the requirements manually, I tried to run sherlock but there was a problem.\r\n```\r\nkali@kali:~/Downloads/sherlock$ python3 sherlock -help\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/home/kali/Downloads/sherlock/sherlock/__main__.py\", line 29, in <module>\r\n    import sherlock\r\n  File \"/home/kali/Downloads/sherlock/sherlock/sherlock.py\", line 18, in <module>\r\n    import requests\r\nModuleNotFoundError: No module named 'requests'\r\n```\r\nI tried to install module 'requests' and still not work.\r\n```\r\nkali@kali:~/Downloads/sherlock$ sudo apt-get install python3-requests\r\nReading package lists... Done\r\nBuilding dependency tree       \r\nReading state information... Done\r\npython3-requests is already the newest version (2.24.0+dfsg-1).\r\npython3-requests set to manually installed.\r\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\r\n```\r\nHow to solve this?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/873/comments",
    "author": "beesuns",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-11-23T08:44:24Z",
        "body": "This is not an issue with Sherlock. It is an issue with your environment. \r\n\r\nI am closing this issue as invalid because you did not follow the issue template."
      }
    ]
  },
  {
    "number": 770,
    "title": "question: \"has anyone checked the validity of the results by querying own credentials\" ? ",
    "created_at": "2020-09-22T17:03:51Z",
    "closed_at": "2020-09-23T15:10:00Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/770",
    "body": "i can confidently say i do not have a gotinder account, no wattpad , no  facebook nor twitter account  yet my gmail has,  it seems ..\r\nBut How  ?\r\n are mx records publicly available, scrapers and spammer or there's some related connection to anyone i might have emailed or even called ..\r\nbut the app/script  doesn't run checks via \"mxtools\" ,\"riskiq\" or at \"haveibeenpawned\"  it asks the sites themselves if members/users are registered and have a an actual account and page to access it..\r\nright ?\r\n\r\ni can only imagine how uncomfortable a situation one could land in by jumping to conclusions ",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/770/comments",
    "author": "maximlomans",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-09-23T15:10:00Z",
        "body": "> has anyone checked the validity of the results by querying own credentials?\r\n\r\nYes, and I have found some false positives but they are in the processes of being fixed."
      }
    ]
  },
  {
    "number": 726,
    "title": "Errors on Facenama and Cloob",
    "created_at": "2020-08-16T21:49:50Z",
    "closed_at": "2020-08-17T04:26:01Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/726",
    "body": "The script outputs \"Error Connecting\" for those two platforms",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/726/comments",
    "author": "busybox11",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-08-17T04:26:01Z",
        "body": "@busybox11 That is not an issue with Sherlock. You are getting that error because your computer is unable to connect with the site. This could be because of slow internet connection."
      },
      {
        "user": "busybox11",
        "created_at": "2020-08-17T16:58:20Z",
        "body": "Well, I don't think this is an error from my computer, since it is running from Google Cloud Engine..."
      },
      {
        "user": "sdushantha",
        "created_at": "2020-08-17T17:04:10Z",
        "body": "> Well, I don't think this is an error from my computer, since it is running from Google Cloud Engine...\r\n\r\n@busybox11 The connection errors are not large problems. They tend to go away if you try running Sherlock a couple of times. The site might be a little slow to respond. It's not really a problem with Sherlock"
      }
    ]
  },
  {
    "number": 706,
    "title": "Using Display Name's Instead of @'s / Username",
    "created_at": "2020-08-08T12:44:05Z",
    "closed_at": "2020-08-08T13:57:44Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/706",
    "body": "It would be easier if we can search some one's social media account's with a Display name/Nickname e.g If  I was trying to find someone on Instagram we could use their Real Name since we cant add Spaces or it will be identified as another user when starting the search.",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/706/comments",
    "author": "Xenoy017",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-08-08T13:57:44Z",
        "body": "It will be identified as another user when starting the search. Usernames are more unique than display names"
      }
    ]
  },
  {
    "number": 705,
    "title": "Question: Sherlock Slow",
    "created_at": "2020-08-08T10:16:09Z",
    "closed_at": "2020-08-08T11:05:47Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/705",
    "body": "if sherlock is being slow, (taking long to load the results) is that your internets fault, your computers, or the websites? idk just a question",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/705/comments",
    "author": "ghost",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-08-08T11:04:55Z",
        "body": "Hey @Flairings!\r\n\r\nGreat question! It usually has to do with your internet speed and the speed of the website. Sometimes certain websites take a long time to respond in certain countries (not sure why). "
      }
    ]
  },
  {
    "number": 702,
    "title": "What happened to the ASCII Banner?",
    "created_at": "2020-08-06T21:39:16Z",
    "closed_at": "2020-08-07T04:31:31Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/702",
    "body": "In the GIF at the README the banner is shown, however, on the latest version it isn't shown",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/702/comments",
    "author": "404oops",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-08-07T04:31:31Z",
        "body": "@YeaToast It was removed a long time ago because it was unnecessary to have. We haven't updated the GIF in the README, because the only difference is that the banner is gone and that the command is slightly different know because of the new directory structure we have."
      }
    ]
  },
  {
    "number": 676,
    "title": "Stuck on the requirements",
    "created_at": "2020-07-25T21:23:03Z",
    "closed_at": "2020-08-06T12:33:00Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/676",
    "body": "Hello, im currently trying to download sherlock and one of the errors ive encountered so far is being stuck on\r\n Running setup.py bdist_wheel for lxml ... / \r\n\r\nAny tips on how to fix this?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/676/comments",
    "author": "Acidic-x",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-07-26T07:01:24Z",
        "body": "Could you please send a screenshot of the command you ran and the error you are getting? This will allow use to further help you out."
      }
    ]
  },
  {
    "number": 671,
    "title": "Issue with downloading Shrelock on Python with Windows 10",
    "created_at": "2020-07-19T14:35:45Z",
    "closed_at": "2020-07-20T18:58:21Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/671",
    "body": "I installed have Python 3.8 (Including pip3) and everytime i try to download sherlock I get a Syntax Error ? I'm new to the coding and really don't know what to do...",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/671/comments",
    "author": "MicrowaveMaster",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-07-20T18:54:11Z",
        "body": "Did make sure to install the needed dependencies? If you haven't, just run the command below:\r\n```\r\npython3 -m pip install -r requirements.txt\r\n```\r\n\r\nIf this doesnt fix the problem, could you send a screenshot or copy and paste the error message you are getting?"
      },
      {
        "user": "MicrowaveMaster",
        "created_at": "2020-07-20T18:58:21Z",
        "body": "I finally got it to work using the google cloud shell, thanks for the reply"
      }
    ]
  },
  {
    "number": 668,
    "title": "-bash: python3: command not found",
    "created_at": "2020-07-10T22:00:46Z",
    "closed_at": "2020-07-12T19:41:34Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/668",
    "body": "When i try to install the requirements i get the error -bash: python3: command not found\r\n\r\nIm using kali linux terminal on windows and i have the newest version of python",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/668/comments",
    "author": "tobi437a",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-07-11T06:13:17Z",
        "body": "Thats strange. What is the output of `python --version` ?\r\nIf the version is something like `3.x.x`, then try installing the requirements like this: `python -m pip install -r requirements.txt`"
      },
      {
        "user": "tobi437a",
        "created_at": "2020-07-12T19:08:43Z",
        "body": "Yeah if i do that i get the error -bash: python: command not found"
      },
      {
        "user": "sdushantha",
        "created_at": "2020-07-12T19:41:34Z",
        "body": "Looks like you did a mistake when installing Python. Could be that Python is not in your `$PATH`. I unfortunately can't help you with installing python, but there are many YouTube videos which explains very well on how you can properly install it.\r\n\r\nClosing this as it has nothing to do with Sherlock."
      }
    ]
  },
  {
    "number": 658,
    "title": "ERROR: Cannot uninstall 'stem'. ",
    "created_at": "2020-06-25T23:09:35Z",
    "closed_at": "2020-07-30T15:50:47Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/658",
    "body": "When I run the:\r\n\r\n`$ python3 -m pip install -r requirements.txt`\r\n\r\ncommand to finish setting up Sherlock, I get the following error while trying to uninstall stem:\r\n\r\n```\r\nAttempting uninstall: stem\r\nFound existing installation: stem 1.7.1\r\nERROR: Cannot uninstall 'stem'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.\r\n```\r\n\r\nI've tried locating packages named stem but I can't find any. What am I supposed to do here?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/658/comments",
    "author": "DnDRogue",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-07-02T16:18:07Z",
        "body": "Hey there @DnDRogue, I have never seen that type error before.\r\nYou could try uninstalling `stem` first, `python3 -m pip uninstall stem`, and then run `python3 -m pip install -r requirements.txt`?\r\n\r\nLet me know what happens, I'm curious to know."
      }
    ]
  },
  {
    "number": 644,
    "title": "Getting stuck at Coroflot",
    "created_at": "2020-06-13T23:15:39Z",
    "closed_at": "2020-07-28T07:38:04Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/644",
    "body": "Hey guys,\r\nI haven't been able to use this as it get stuck at Coroflot. Does anyone getting the same issue?\r\nAny workaround? I tried to delete and reinstall but issue persists. Running on Kali Linux.\r\nCheers",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/644/comments",
    "author": "Fabruk",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-06-20T13:49:31Z",
        "body": "Hi @Fabruk :)\r\n\r\nThe reason for Sherlock getting stuck at Coroflot could be because of your internet connection because I just ran a fresh install of Sherlock and everything seems to be working smoothly. "
      },
      {
        "user": "sdushantha",
        "created_at": "2020-07-28T07:38:04Z",
        "body": "Closing this issue assuming that it has been solved. And I'm not expecting a reply because that account was created on the same day this issue was made, so I assume it's a throw away account.\r\n\r\nI know assuming is not good, but that's the only thing I can do in order to clean up the issues in this repo."
      }
    ]
  },
  {
    "number": 636,
    "title": "Couldn't access data file data.json",
    "created_at": "2020-06-04T03:13:21Z",
    "closed_at": "2020-07-30T15:38:23Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/636",
    "body": "Im having problems where know when i try to use Sherlock, the prompt problem while attempting to access data file, data.json, o im not sure whats wrong?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/636/comments",
    "author": "AC1370",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2020-06-04T10:56:57Z",
        "body": "I am not clear what problem you are having.  Did you run the procedure in the readme file?  If so, what error message did you get?"
      },
      {
        "user": "Devil-vx",
        "created_at": "2020-06-15T14:12:52Z",
        "body": "Im having problems where know when i try to use Sherlock, the prompt problem while attempting to access data file, data.json, o im not sure whats wrong. I am using in android termux ."
      },
      {
        "user": "sdushantha",
        "created_at": "2020-07-30T15:38:23Z",
        "body": "Im closing this issue as it hasnt seen any activity and the author of this issue seems to have used a throw away account because the issue was created 2 days after the creation of the account and has not seen any activity since."
      }
    ]
  },
  {
    "number": 633,
    "title": "Names with spaces not working on SoundCloud",
    "created_at": "2020-06-02T04:05:42Z",
    "closed_at": "2020-08-07T16:15:46Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/633",
    "body": "Usernes with a space are not found on SoundCloud.com",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/633/comments",
    "author": "Vanceagher",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-06-20T13:52:25Z",
        "body": "Hi @Vanceagher,\r\n\r\nUsernames tend to not have spaces. They are usually a single string of alphanumeric characters and sometimes including underscores and certain special characters.\r\nSo usernames with spaces not working on SoundCloud is normal behavior. I doubt it works on any other site as well."
      }
    ]
  },
  {
    "number": 611,
    "title": "Getting Stucked in Letterboxd",
    "created_at": "2020-05-17T11:08:19Z",
    "closed_at": "2020-06-28T12:03:58Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/611",
    "body": "",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/611/comments",
    "author": "bossauh",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-06-20T14:29:16Z",
        "body": "Hey @bossauh,\r\n\r\nIm really sorry for the late reply. Are you still having this issue? I just tested everything it seems like everything it fine on my end. I think the reason why Letterboxd is getting stuck is because of your internet connection."
      }
    ]
  },
  {
    "number": 606,
    "title": "\"Error: Command errored out with exit status 1:\"",
    "created_at": "2020-05-13T10:44:57Z",
    "closed_at": "2020-08-07T20:04:29Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/606",
    "body": "here is the full error message when installing  ERROR: Command errored out with exit status 1:\r\n     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-r8m7514n/bs4/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-r8m7514n/bs4/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-install-r8m7514n/bs4/pip-egg-info\r\n         cwd: /tmp/pip-install-r8m7514n/bs4/\r\n    Complete output (11 lines):                                            \r\n    Traceback (most recent call last):                                     \r\n      File \"<string>\", line 1, in <module>                                 \r\n      File \"/usr/lib/python3/dist-packages/setuptools/__init__.py\", line 15, in <module>                                                              \r\n        from setuptools.extern.six import PY3, string_types                \r\n      File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load    \r\n      File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked                                                                      \r\n      File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked    \r\n      File \"<frozen importlib._bootstrap_external>\", line 779, in exec_module                                                                         \r\n      File \"<frozen importlib._bootstrap_external>\", line 915, in get_code \r\n      File \"<frozen importlib._bootstrap_external>\", line 973, in get_data \r\n    OSError: [Errno 5] Input/output error                                  \r\n    ----------------------------------------                               \r\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                      \r\n\r\nhow can i fix this??",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/606/comments",
    "author": "LewisTheKali",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-05-14T07:35:41Z",
        "body": "@LewisTheKali Could you please provide which provide what command you ran whcih caused this error? Also, can you tell us what the output of this command?\r\n```\r\npython3 --version\r\n```"
      }
    ]
  },
  {
    "number": 604,
    "title": "Permission denied",
    "created_at": "2020-05-12T04:13:29Z",
    "closed_at": "2020-07-12T19:56:36Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/604",
    "body": "I was getting the \"permission denied\" prompt on windows 10 with Git Bash when trying to install the requirements after cloning the repo. I bypassed this by installing mitproxy. Now however, I get permission denied when trying to run a \"python3 sherlock.py username\" command. Not sure how I can even fix this on my end?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/604/comments",
    "author": "chromechris",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-05-12T09:34:30Z",
        "body": "To install the requirements, run this command:\r\n```\r\npip install --user -r requirements.txt\r\n```\r\n\r\nIf you are using the latest version of Sherlock all you have to do is run this:\r\n```\r\npython3 sherlock username\r\n```\r\nYou dont need the \".py\" extension."
      },
      {
        "user": "hoadlck",
        "created_at": "2020-05-12T10:48:40Z",
        "body": "If you are on Windows, you should use `python` not `python3`."
      },
      {
        "user": "sdushantha",
        "created_at": "2020-07-12T19:56:36Z",
        "body": "This issue is 2 months old and there doesn't seem to be any updates from @chromechris. I will assume that they have successfully fixed the issue that they were having. I am closing this so that the list of issues can be kept nice and tidy."
      }
    ]
  },
  {
    "number": 598,
    "title": "sherlock coding",
    "created_at": "2020-05-09T02:58:02Z",
    "closed_at": "2020-07-30T15:45:00Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/598",
    "body": "after i type in all the codes to find a username using github sherlock, it says \"(null): can't open file 'sherlock.py': [Errno 2] No such file or directory\" this is after i typed in the name to find all social media platforms of someone. How do i resolve this issue?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/598/comments",
    "author": "someoneouttheretrying",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2020-05-09T04:12:49Z",
        "body": "As part of the restructure, the command to invoke Sherlock from the root of the Git repo has changed.  Now, you type `python sherlock` instead of `python sherlock.py`.\r\n\r\nThe commands have been updated in the readme."
      },
      {
        "user": "someoneouttheretrying",
        "created_at": "2020-05-09T04:21:32Z",
        "body": "i just tried it and it says \"SyntaxError: invalid syntax\"\r\n"
      },
      {
        "user": "hoadlck",
        "created_at": "2020-05-09T12:38:26Z",
        "body": "I assume that this new error message is coming from Python?  Have you performed the installation instructions in the readme?  Are you running python 3.6 or later?"
      }
    ]
  },
  {
    "number": 597,
    "title": "add lastName in usrename",
    "created_at": "2020-05-07T16:35:13Z",
    "closed_at": "2020-05-08T09:59:44Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/597",
    "body": "How do I add Lastname to a username. ex: python3 sherlock Joe Goldberg. now it just considers joe as first username and Goldberg as the second username, but they are single username",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/597/comments",
    "author": "ghost",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2020-05-07T16:47:56Z",
        "body": "I am not sure how many sites allow spaces in the username.  But, you need to quote the argument in the shell.  Like the following:\r\n```\r\n%  python3 sherlock \"Joe Goldberg\"\r\n```"
      }
    ]
  },
  {
    "number": 535,
    "title": "Could not find a version that satisfies the requirement requests-futures (from versions: )",
    "created_at": "2020-02-03T15:13:00Z",
    "closed_at": "2020-05-09T16:47:59Z",
    "labels": [
      "question",
      "environment"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/535",
    "body": "i tried all method but nothing is working and same error is showing again and again",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/535/comments",
    "author": "dhruv-atreya",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-02-03T16:48:44Z",
        "body": "Try doing this:\r\n```\r\n# Try upgrading pip in case there is a newer version\r\n$ python3 -m pip install --upgrade pip\r\n\r\n# Install the latest version of requests-futures\r\n$ python3 -m pip install \"requests-futures==1.0.0\" --force-reinstall\r\n```"
      },
      {
        "user": "hoadlck",
        "created_at": "2020-05-09T16:47:59Z",
        "body": "Closing this out as it appears to be an install issue instead of something wrong with Sherlock."
      }
    ]
  },
  {
    "number": 530,
    "title": "Error message",
    "created_at": "2020-01-23T08:00:44Z",
    "closed_at": "2020-05-09T16:47:03Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/530",
    "body": "```\r\n$ python3 sherlock.py -h\r\n  File \"sherlock.py\", line 66\r\n    Fore.GREEN + f\"] {title}\" +\r\n                            ^\r\nSyntaxError: invalid syntax\r\n```",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/530/comments",
    "author": "avik1991",
    "comments": [
      {
        "user": "PeskyPotato",
        "created_at": "2020-01-23T08:39:50Z",
        "body": "Hello, \r\n\r\nHave you cloned Sherlock straight from the master branch? Can you make sure there were no changes made locally to the code. I just fetched the latest commit and it worked for me on two different machines. \r\n\r\n: )"
      },
      {
        "user": "hoadlck",
        "created_at": "2020-01-23T11:31:23Z",
        "body": "Looks like you are trying to run Sherlock with a version of Python before 3.6.  If you type, `python3 --version`, what do you get?"
      },
      {
        "user": "aden-webster",
        "created_at": "2020-01-29T19:44:58Z",
        "body": "> Looks like you are trying to run Sherlock with a version of Python before 3.6. If you type, `python3 --version`, what do you get?\r\n\r\nI am getting the same error, my python version is 3.73."
      },
      {
        "user": "darjaallora",
        "created_at": "2020-03-27T23:13:18Z",
        "body": "I also got this error; replicates when calling \"python\" instead of \"python3\" on my home machine where \"python\" defaults to 2.6 even though python 3.7 is installed, for some ungodly reason.  Invoking \"python3\" works as expected."
      },
      {
        "user": "hoadlck",
        "created_at": "2020-05-09T16:47:03Z",
        "body": "Closing this out as it appears to be an install issue instead of something wrong with Sherlock."
      }
    ]
  },
  {
    "number": 359,
    "title": "demo link in readme.md",
    "created_at": "2019-11-23T21:26:15Z",
    "closed_at": "2020-02-18T11:05:51Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/359",
    "body": "In the readme.md file , when I click on the Demo link, a message pops up saying that it is not a secure connection and that criminals might steal information. Anyone else have this issue ?",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/359/comments",
    "author": "Niagara1000",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2019-11-24T00:07:29Z",
        "body": "Their SSL certificate expired on 2019-11-23.  They are using Let's Encrypt, but they must not have set up the cron job that automatically renews it.\r\n\r\nI am not sure what to do with this.  If they don't renew the certificate somewhat soon, we should probably remove the link.\r\n\r\n@FlorianDietz You added the link to elody.com originally.  Do you know what is up with the site?"
      },
      {
        "user": "dpieski",
        "created_at": "2019-12-19T21:18:53Z",
        "body": "@hoadlck You can close now. They have a new cert as of 2019-11-24."
      }
    ]
  },
  {
    "number": 310,
    "title": "Error Line 628 ",
    "created_at": "2019-08-18T21:21:33Z",
    "closed_at": "2019-09-05T11:59:51Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/310",
    "body": "sherlock Username$ python3 sherlock.py user123\r\nTraceback (most recent call last):\r\n  File \"sherlock.py\", line 620, in <module>\r\n    main()\r\n  File \"sherlock.py\", line 374, in main\r\n    f\"{requests.__description__}:  {requests.__version__}\\n\" + \\\r\nAttributeError: module 'requests' has no attribute '__description__'\r\nComputer:sherlock Username$ \r\n\r\n\r\n\r\n\r\nIm probably being an idiot and messed something up",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/310/comments",
    "author": "allepicondor",
    "comments": [
      {
        "user": "DecryptingElectrons",
        "created_at": "2019-08-23T03:33:36Z",
        "body": "Compare your requests version to the current"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-08-25T01:01:44Z",
        "body": "@allepicondor are you still having problems?"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-09-05T11:59:51Z",
        "body": "This looks like a case of not having the proper dependencies installed.  Since we have not heard anything back, I am closing the issue."
      }
    ]
  },
  {
    "number": 308,
    "title": "Massive Issues",
    "created_at": "2019-08-14T19:34:28Z",
    "closed_at": "2020-05-09T16:51:20Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/308",
    "body": "Getting Errors Connecting to :\r\n Aptoide, Basecamp, Carbonmade, ColourLovers, Crevado, Itch.Io, Jimdo, Rajce.net, Webnode, Wix. As of today it is also crashing and causing complete system freezes on both systems I am utilizing it on, 1 is a Virtual Box Kali Linux 2.0 the other is a dedicated Kali Linux 2.0 system . \r\n\r\nAnother common problem is if you use say \"First.Lastname\" it will get results for say www.com/independent.academia.edu/FIRSTNAME instead of www.com/independent.academia.edu/FIRSTNAME.LASTNAME \r\n\r\nthis is on quite a few of the search as well. \r\n\r\nI have also observed that when you run FirstName.LastName say\r\nPython3 sherlock.py firstname.lastname -r it produces \"Illegal Username Format\" \r\n\r\nanother issue is i'll go to run sherlock and it returns only 3 results and ends. \r\n\r\nDistributor ID:\tKali\r\nDescription:\tKali GNU/Linux Rolling\r\nRelease:\t2019.3\r\nCodename:\tkali-rolling\r\n\r\nusing latest version of sherlock ",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/308/comments",
    "author": "ghost",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2019-08-25T01:00:48Z",
        "body": "It does sounds like there is some issue with your environment.  Some sites do not respond if they don't like the IP address that you are coming from.\r\n\r\nThe error message with the \"Illegal Username Format\" is because some sites do not accept usernames with a \".\" in them.  If Sherlock said that there was no username like that (which would be true), it would still be misleading: no one could have a username with a \".\" at that site.\r\n\r\nUnfortunately, we do not have the checking for the valid username format for all sites.  So, some messages reporting available usernames may not be actually true."
      },
      {
        "user": "hoadlck",
        "created_at": "2019-12-24T23:10:03Z",
        "body": "Can you try it now with the latest content on master (version 0.10.0)? In #471, I placed a limit on the number of threads that can be allocated. And, it did not seem to make any difference on performance.\r\n\r\nOther people have been having other symptoms, but I wonder if this bug may have been what you have been seeing."
      },
      {
        "user": "hoadlck",
        "created_at": "2020-05-09T16:51:20Z",
        "body": "Closing this issue out, as I believe it was involved in the earlier versions of Sherlock that did not place any limit on the number of workers when doing requests.  As more sites were added, it would bring any computer to its (virtual) knees."
      }
    ]
  },
  {
    "number": 300,
    "title": "File \"sherlock.py\", line21, in <module>",
    "created_at": "2019-08-09T03:02:14Z",
    "closed_at": "2019-10-20T16:09:40Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/300",
    "body": "Hi.  Having problems with the following feedback basic search paramater:\r\n\r\n```\r\npython3 sherlock.py user\r\n```\r\n```\r\nError message is as follows:\r\nTraceback (most recent call last):\r\nFile \"sherlock.py\", line 21, in <module>\r\nimport requests\r\nModuleNotFoundError:  No module named 'requests'.\r\n```\r\n\r\nCan anyone help me to solve this?  Thanks.",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/300/comments",
    "author": "TechGirl007",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2019-08-09T06:20:40Z",
        "body": "Hey @TechGirl007 \r\n\r\nHave you installed all the required modules by running this command?\r\n```bash\r\n$ pip3 install -r requirements\r\n```"
      },
      {
        "user": "TechGirl007",
        "created_at": "2019-08-12T08:24:35Z",
        "body": "Hi @sdushantha \r\nYes.  :(  Did it twice - so not sure if that is the problem!  Says all installed!"
      },
      {
        "user": "dewjiguang",
        "created_at": "2019-08-21T08:46:14Z",
        "body": "i met the same problem with you, so,have you solve it ?"
      },
      {
        "user": "TechGirl007",
        "created_at": "2019-08-25T03:40:33Z",
        "body": "Hi @dewjiguang   Yup...still same problem. There is no module called requests.  I installed the module into python but the installation seems to go to a file of python2.7 that came with Kali originally.  I have a few other ideas to install the module in python 3.7.  But at the moment... I'm still getting the same reading even with the new request module that I installed.  Any help would be appreciated!  Thanks"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-08-25T12:33:43Z",
        "body": "You need to have the dependencies installed for Python 3.7.  If you are actually running the pip for Python 2.7, the dependencies will not change for Python 3.7.\r\n\r\nTry typing the following:\r\n\r\n```\r\n% pip3 --version\r\npip 19.0.3 from c:\\python36\\lib\\site-packages\\pip (python 3.6)\r\n```\r\n\r\nYour results will be different, but it should show you the version of Python and where the main Python engine is installed."
      },
      {
        "user": "iz-rtx",
        "created_at": "2019-08-27T06:39:11Z",
        "body": "Same problem here for me , I'm on UBUNTU 19.04 with python3.7\r\nError:\r\nTraceback (most recent call last):\r\n  File \"sherlock.py\", line 21, in <module>\r\n    import requests\r\n  File \"/home/qphy/.local/lib/python3.7/site-packages/requests/__init__.py\", line 43, in <module>\r\n    import urllib3\r\nModuleNotFoundError: No module named 'urllib3'"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-08-27T11:24:30Z",
        "body": "@Arsaamkhan you need to have the requirements installed.  You can see from the error message that your Python install does not have urllib3, and Sherlock needs that.\r\n\r\nAs it says in the readme, you have to run a command like the below:\r\n```\r\n$ python3 -m pip install -r requirements.txt\r\n```"
      },
      {
        "user": "iz-rtx",
        "created_at": "2019-08-27T18:12:22Z",
        "body": "@hoadlck the message in terminal is displayed as\r\nRequirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (1.24.1)\r\n\r\nand i had installed all the packages that are mentioned in the requirements.txt\r\nwith the same command you mentioned above.\r\non which system have u tested sherlock  ?\r\nafter that i had tried sherlock in Termux (Android App) and it worked. "
      },
      {
        "user": "ghost",
        "created_at": "2019-09-15T12:10:10Z",
        "body": "@TechGirl007 try running sherlock on Parrot os it worked for me"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-10-20T16:09:40Z",
        "body": "This issue appears to be an environmental issue rather than a problem with Sherlock itself.  It also has been hanging out for some time.  So, I am closing it out now to remove the clutter."
      },
      {
        "user": "Csql2",
        "created_at": "2024-04-23T15:12:47Z",
        "body": "I have the same error"
      }
    ]
  },
  {
    "number": 296,
    "title": "Username with Space",
    "created_at": "2019-08-03T20:00:24Z",
    "closed_at": "2019-08-08T18:54:03Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/296",
    "body": "How I can search a Username with a Space\r\n",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/296/comments",
    "author": "T2brozz",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2019-08-03T23:42:05Z",
        "body": "You just need to quote the user name on the command line.  Here is an example using a Git Bash shell on Windows 10:\r\n```\r\npython -u sherlock.py --site twitter \"name space\"\r\n```\r\n\r\nKeep in mind that there are probably many sites that do not allow spaces in the user name.  Sherlock does not have many of the validity checks configured, so a name that may claim to be available might actually  be illegal."
      },
      {
        "user": "T2brozz",
        "created_at": "2019-08-08T18:54:00Z",
        "body": "Thanks\r\n"
      },
      {
        "user": "rama25",
        "created_at": "2022-08-12T18:20:09Z",
        "body": "`python sherlock \"username\"`\r\nthis command works for username with spaces and extracts info about users from all the sites which are in sites.md"
      }
    ]
  },
  {
    "number": 290,
    "title": "An error",
    "created_at": "2019-07-28T16:59:23Z",
    "closed_at": "2019-08-25T12:38:30Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/290",
    "body": "My computer tells me 'pip3' is not recognized as an internal or external command,\r\noperable program or batch file. if someone could help me out hat would be great",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/290/comments",
    "author": "joedouglas5305",
    "comments": [
      {
        "user": "tdh8316",
        "created_at": "2019-07-29T00:07:54Z",
        "body": "Use `python -m pip3`"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-08-25T12:38:30Z",
        "body": "Appears to be an installation issue, so I am closing this."
      }
    ]
  },
  {
    "number": 222,
    "title": "Mac Install Issue",
    "created_at": "2019-07-11T00:47:47Z",
    "closed_at": "2019-07-16T00:41:57Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/222",
    "body": "Doing the pip3 install requirement.txt command results in this error:\r\n```\r\n ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)\r\nERROR: No matching distribution found for requirements.txt\r\n```\r\nAny idea how to fix it? Thanks",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/222/comments",
    "author": "StevenMonty",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2019-07-11T04:13:26Z",
        "body": "Looks like you missed the ```-r``` option on the command line.  \r\n\r\nThe command is \r\n```pip3 install -r requirements.txt```"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-07-16T00:41:57Z",
        "body": "Looks like this was just a missing option on the command line. So, I am closing the issue."
      },
      {
        "user": "DrewCode00",
        "created_at": "2019-07-18T09:02:07Z",
        "body": "Hi, I'm trying to install Sherlock on Android using termux but I get error when I install \r\npip3 install -r requirements.txt\r\n\r\n\" error: command 'arm-linux-androideabi-clang' failed with exit status 1\r\n    ----------------------------------------\r\nERROR: Command \"/data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='\"'\"'/data/data/com.termux/files/usr/tmp/pip-install-h6re8a7a/lxml/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-ldgldbx4/install-record.txt --single-version-externally-managed --compile\" failed with error code 1 in /data/data/com.termux/files/usr/tm     \""
      }
    ]
  },
  {
    "number": 165,
    "title": "Ideas On Choosing The Perfect Unclaimed Username?",
    "created_at": "2019-02-06T21:58:24Z",
    "closed_at": "2023-03-12T21:22:02Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/165",
    "body": "One of the pains in delivering on #37 is that I need to figure out an unclaimed username (to verify that Sherlock can correctly detect that a given username is open).\r\n\r\nI have been using \"noonewouldeverusethis7\" as this username, because...who would use something like that?  However, sometime in the last couple of days, someone has claimed that username on BuzzFeed and Canva.  The irony is not lost on me.\r\n\r\nSo, my questions are twofold:\r\n1. Does anyone have ideas on how to choose usernames that no one else has claimed?\r\n2. Does anyone know how these names might get claimed just from Sherlock doing queries against them?  I find it hard to believe that \"noonewouldeverusethis7\" just randomly got claimed.",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/165/comments",
    "author": "hoadlck",
    "comments": [
      {
        "user": "mpieters93",
        "created_at": "2019-02-07T08:19:31Z",
        "body": "I was thinking about generating a random alphabetical string, testing, and repeating this process once or twice.\n\nThis way, we get usernames that are very unlikely to be in use, and prevent people from claiming usernames that are in the source of Sherlock.\n\nI think I could submit a pull request this weekend for the false positive testing, if no one else wants this issue of course.\n\nPlease let me know your thoughts.\n\nAfterthought: perhaps we could also generate random usernames based on the regex that describes valid usernames per website, but that might be a V2 of this functionality?"
      },
      {
        "user": "hoadlck",
        "created_at": "2019-02-07T12:48:14Z",
        "body": "The current tests only check one username per site query. So, the test for unclaimed detection would have to be changed.  If the tests always had to try multiple usernames to find an unclaimed one, it would really extend the test times.\r\n\r\nI guess what I am really worrying about is how exactly the existing site got the \"noonewouldeverusethis7\" username. If this is something that is happening on the site side, then the entire approach of Sherlock is called into question.  It is only going to work if it was someone in the Sherlock community that is defining them."
      },
      {
        "user": "TheYahya",
        "created_at": "2019-02-08T05:53:52Z",
        "body": "using a username that can't be used in the sites could be an option, like username with less than 3 chars or more than 52 chars in some sites."
      },
      {
        "user": "irazasyed",
        "created_at": "2019-08-09T16:32:31Z",
        "body": "@hoadlck You don't have to generate multiple usernames for every site. You can generate one random string and reuse it for every site. It won't add up in terms of test times if you just reuse it just like you're already doing for all the sites. Hardly a few have different unclaimed usernames but otherwise, it's mostly the same. \r\n\r\nFurther, you can explore Faker package to generate a username + append a random string/digits to make it more unique and testable but I don't really see any reason to do that since the random string should just be fine anyway.\r\n\r\n@TheYahya Some sites will throw a different error for such kinda usernames, unfortunately. So we can't really rely on that.\r\n\r\nTo make the random string work more accurately, we could also rely on the regex in the data to generate the string that fits within the regex pattern (Ex: in cases where the site requires min. 3 chars and max 8 chars for a username -- anything beyond will throw a completely different error, happens with PayPal for example)."
      },
      {
        "user": "z1nc0r3",
        "created_at": "2022-07-06T18:11:20Z",
        "body": "Using a somewhat long username (more than 50 chars or something) may be an quite good approach."
      },
      {
        "user": "cclauss",
        "created_at": "2022-07-07T10:54:37Z",
        "body": "`import time ; f\"user{time.time_ns()}\".rstrip('0')` --> user1657191108413085\r\n\r\nIt will be difficult for spammers to guess which nanosecond the test will run."
      },
      {
        "user": "sdushantha",
        "created_at": "2023-03-12T21:22:01Z",
        "body": "We have removed unclaimed usernames from `data.json`. For the sites that need it for the tests, we use `exrex` to generate a random username based on the `regexCheck` regex :)"
      }
    ]
  },
  {
    "number": 578,
    "title": "Instagram do not works",
    "created_at": "2020-04-08T21:17:54Z",
    "closed_at": "2020-05-09T16:42:53Z",
    "labels": [
      "bug",
      "help wanted"
    ],
    "url": "https://github.com/sherlock-project/sherlock/issues/578",
    "body": "# Sherlock doesnt find any username for instagram.\r\n\r\nI am looking for a user who has an instagram account but sherlock cannot find the account with the same username.",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/578/comments",
    "author": "fntkg",
    "comments": [
      {
        "user": "sdushantha",
        "created_at": "2020-04-09T14:10:37Z",
        "body": "@fntkg This is a strange issue. Someone did email me about this but I haven't been able to figure out why this is happening. I am able to check if a username exists on Instagram on a seperate script, but it fails when using Sherlock."
      },
      {
        "user": "tech2blog",
        "created_at": "2020-04-26T18:56:48Z",
        "body": "Yes, for Instagram, it is not showing username. \r\n\r\n```\r\n[-] Instagram: Not Found!\r\n```"
      },
      {
        "user": "richardgetz",
        "created_at": "2020-05-06T19:05:13Z",
        "body": "Okay I figured it out. Instagram has an extra measure in place that doesn't allow HEAD requests. I'll fork and make a pull request. #593 "
      },
      {
        "user": "hoadlck",
        "created_at": "2020-05-09T16:42:53Z",
        "body": "This has been included in #599 as there was a non-trivial merge in including #593.  "
      },
      {
        "user": "zencore77",
        "created_at": "2021-03-07T04:34:47Z",
        "body": "same issue"
      },
      {
        "user": "demonshead666",
        "created_at": "2021-06-08T04:19:01Z",
        "body": "As of 9th June 2021, it still doesn't work for Instagram, displaying site not found"
      },
      {
        "user": "moraddart5",
        "created_at": "2021-07-19T19:38:14Z",
        "body": "Still facing the same issue \r\n"
      },
      {
        "user": "Akr0m",
        "created_at": "2025-01-13T14:38:29Z",
        "body": "Still facing the same issue"
      }
    ]
  },
  {
    "number": 202,
    "title": "Prevent copying of venv folder in the Docker image",
    "created_at": "2019-04-24T21:28:20Z",
    "closed_at": "2020-06-20T20:07:02Z",
    "labels": [
      "help wanted"
    ],
    "url": "https://github.com/sherlock-project/sherlock/pull/202",
    "body": "After diving into the current image I noticed that the `venv` was copied in there. This PR should prevent that from happing in future builds.\r\n\r\n### What has been done:\r\n- added venv folder to the .dockerignore\r\n\r\n### Notes:\r\n- I also noticed that the current image on docker hub has a layer for `RUN /sbin/apk add tor`. Is this supposed to be there? Maybe we can rebuild the image to reflect the Dockerfile in the repository. ",
    "comments_url": "https://api.github.com/repos/sherlock-project/sherlock/issues/202/comments",
    "author": "nstapelbroek",
    "comments": [
      {
        "user": "hoadlck",
        "created_at": "2019-07-15T03:05:24Z",
        "body": "I have not used Docker, so I cannot provide a meaningful review. Perhaps @cblument can take a look?"
      },
      {
        "user": "paulodiovani",
        "created_at": "2019-12-04T13:56:09Z",
        "body": "Suggestion: Setup auto build on docker hub.\r\n@TheYahya  should do it.\r\n\r\nAnother (better) option would be to create an organization on Docker Hub as well.\r\n\r\n"
      },
      {
        "user": "cblument",
        "created_at": "2019-12-15T03:40:49Z",
        "body": "This is safe to merge"
      }
    ]
  }
]